IFACE=wlan0
# Port for gs stats (if available)
UDP_PORT=12345
#
PING_DEST=192.168.0.10
# bitrate command (must include exactly one "%d" for bitrate in kbps)
API_CMD=wget -qO- "http://127.0.0.1/api/v1/set?video0.bitrate=%d" >/dev/null 2>&1
# Base bitrates (kbps) for MCS 0 - 7 at 20-MHz
PR=6500,13000,19500,26000,39000,52000,58500,65000
# Throughput %
THROUGHPUT_PCT=29
# Percentage thresholds for MCS 0..7 (lower-bounds)
THRESH_EU=00,18,22,27,33,40,48,56
THRESH_AU=00,20,30,38,50,63,75,88
THRESH_BU=00,20,30,38,50,63,75,88
# MCS caps 20MHz
MAX_MCS_EU=4
MAX_MCS_AU=2
MAX_MCS_BU=4
# MCS caps 40MHz
MAX_MCS_40_EU=3
MAX_MCS_40_AU=1
MAX_MCS_40_BU=3
# Max power per MCS
PWR_EU=2400,2200,2000,1750,1500,1450,1400,1300
PWR_AU=-4000,-3800,-,3600,-3300,-3000,-2500,-2000
PWR_BU=1800,1600,1500,1400,1300,1200,1100,1000
# Which rssi to use if more than one available: [lowest, highest, both, uplink, downlink]
MCS_SOURCE=downlink
# Upwards hysterestis (stickyness)
H=10
# Number of 0.1-s loops without UDP (DownLQ) before falling back to proc-RSSI (UpLQ)
UDP_TIMEOUT_LOOPS=10
# Loops between re-probing channel width
REFRESH_CNT=21
# Loops between OSD writes
STATUS_CNT=1
# Font/position parameters
OSD_PARAMS=&G8&L31&F24
# aalink OSD: 0 none, 1 basic, 2 detailed
OSD_LEVEL=3
SHOW_SIGNAL_BARS=true
EXTERNAL_OSD=0
ACTIVE_IP=192.168.0.10
REDUCED_POWER_MODE=0
ENABLE_BR_CUT=0
ENABLE_FPS_CUT=0
PUBQ_VERY_LOW=500
PUBQ_LOW=1500
