# antenna‑OSD configuration
# leave any key out to fall back to the built‑in default

info_file   = /proc/net/rtl88x2eu/wlan0/trx_info_debug
out_file    = /tmp/MSPOSD.msg
interval    = 0.25
bar_width   = 37
top         = 80
bottom      = 20
osd_hdr     =  &F34&L20
ping_ip     = 192.168.0.10
start_sym   = [
end_sym     = ]
empty_sym   = .
show_stats_line = 1   # set to 0 to hide the TEMP|STATS|CPU line
#osd_hdr        =  &F34&L20
osd_hdr2       =  &F34&L20
#sys_msg_hdr    =  &F24&L60
#system_msg     =  Hello pilot!
rssi_control = 1

rssi_range0_hdr = &F34&L10 
rssi_range1_hdr = &F34&L10 
rssi_range2_hdr = &F34&L40 
rssi_range3_hdr = &F34&L40
rssi_range4_hdr = &F34&L20
rssi_range5_hdr = &F34&L20
