# commands.conf  (no spaces before the colon)
set_ssid:fw_setenv ssid
set_password:fw_setenv pass
set_channel:set_channel.sh
set_wlanpower:set_power.sh
set_mode:set_mode.sh
reboot:/sbin/reboot
sysinfo:ipcinfo
