# commands.conf  (no spaces before the colon)
set_ssid:fw_setenv ssid
set_password:fw_setenv pass
set_channel:set_channel.sh
set_wlanpower:fw_setenv wlanpwr
set_mode:fw_setenv mode
reboot:/sbin/reboot
sysinfo:ipcinfo
