# commands.conf  (no spaces before the colon)
set_ssid:set_wlanssid.sh
set_password:set_wlanpass.sh
set_channel:set_channel.sh
set_wlanpower:set_power.sh
set_mode:set_mode.sh
reboot:reboot -d 1 -f
sysinfo:webinfo.sh > /tmp/webui.log
set_tty:set_tty.sh
set_video:set_video.sh
control_cmd:control_cmd.sh
set_osd:set_osd.sh
ota:ota.sh
value:aalink_throughput:sed -n 's/^THROUGHPUT_PCT=\(.*\)/\1/p' /etc/aalink.conf
value:aalink_font_size:sed -n -E 's|^OSD_PARAMS=.*&F([0-9]+).*|\1|p' /etc/aalink.conf
value:aalink_osd_level:sed -n 's/^OSD_LEVEL=\(.*\)/\1/p' /etc/aalink.conf
value:aalink_signalbar:sed -n 's/^SHOW_SIGNAL_BARS=\(.*\)/\1/p' /etc/aalink.conf
value:tx_power:set_power.sh get_current
masterip:set_masterip.sh
vtx_adapter_start:adapter start
set_mcs:set_mcs.sh
set_apalink:set_apalink.sh
set_externalosd:set_externalosd.sh
