[general]
poll_interval_ms = 200
hysteresis_ms    = 2000
hysteresis_db    = 5
switch_floor_db  = 40
ping_timeout_ms  = 500      
ping_fail_max    = 5
ping_succ_min    = 2
master_iface     = wlan0
http_port        = 8081
html_path        = /etc/linkmgrd.html
sta_poll_file    = /tmp/sta_data.info
#Switch command to run whenever a new active route is given, to be passed to for example aalink. the active IP is given as the first argument.
switch_cmd = /usr/bin/set_active.sh

[sta0]
ip        = 192.168.0.10
rssi_key  = sta0_rssi

[sta1]
ip        = 192.168.0.11
rssi_key  = sta1_rssi
