#!/bin/sh

case "$1" in
	start)
    		killall -q web
   		web --html /etc/webui.html --commands /etc/commands.conf --port 8080 &
		;;

	stop)
		echo "Stopping web..."
		killall -q web
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
