#!/bin/sh

case "$1" in
	start)
    	kill -9 $(pidof overheat_protection.sh)
   		overheat_protection.sh > /dev/null &
		;;

	stop)
		echo "Stopping Overheat Protection..."
		kill -9 $(pidof overheat_protection.sh)
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
