#!/bin/sh

case "$1" in
	start)
       echo "Starting Watchdog..."
    	kill -9 $(pidof service_watchdog.sh)
   		service_watchdog.sh > /dev/null &
		;;

	stop)
		echo "Stopping Watchdog..."
		kill -9 $(pidof service_watchdog.sh)
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
